---
- name: Ensure jq is installed
  ansible.builtin.package:
    name: jq
    state: present

- name: Copy getDbJsonList.sh to remote server and run it using ansible.builtin.script
  ansible.builtin.script:
    cmd: "{{ role_path }}/files/getDbJsonList.sh {{ db_user | default('root') }} {{ db_password | default('your_root_password') }} {{ db_host | default('localhost') }}"
  register: db_json_output

- name: Parse database list JSON
  ansible.builtin.set_fact:
    db_list: "{{ db_json_output.stdout | from_json | dict2items(key_name='name', value_name='value') | selectattr('key', 'equalto', 'databases') | map(attribute='value') | first }}"

- name: Query REST endpoint xyz for each database
  ansible.builtin.uri:
    url: "http://xyz/api/db/{{ item }}"
    method: GET
    return_content: yes
  loop: "{{ db_list }}"
  register: rest_results

- name: Show REST responses
  ansible.builtin.debug:
    var: rest_results.results